require("core.options")
require("core.keymaps")
require("core.colorscheme")

require("plugins-setup")

require("plugins.cmp")
require("plugins.lsp")
require("plugins.bufferline")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.hop")
require("plugins.lualine")
require("plugins.autopairs")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.toggleterm")
-- require("plugins.dashboard")

